version: '3.8'

services:
  osint-dashboard:
    image: python:3.11-slim
    container_name: osint-dashboard
    volumes:
      - .:/app
      - sqlite_data:/app/data
    working_dir: /app
    ports:
      - "8501:8501"
    command: >
      bash -c "pip install -r requirements.txt &&
               streamlit run dashboard.py --server.port 8501 --server.address 0.0.0.0"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}

volumes:
  sqlite_data:
